### ISSUE TITLE
Issues in running the ImageTransform experiment

### ISSUE THREAD

**Issue by shagunsodhani** [mbchang/crl#1]
I am trying to run the experiments related to ImageTransform example. When I run `crl_imagetransform.py`, I get an error saying that the `ppo` module in `learners/centralized.py` is missing. I have been able to run the experiments related to ArithLang example so I think I have set up the code correctly. 

Could you please check if any files/modules were skipped while pushing the code to Github.

**Comment by mbchang** [comment]
Thank you for your question! The `ppo.py` file is uploaded now.

**Comment by shagunsodhani** [comment]
That was very quick! Thank you :)
